# Generated by Django 5.2 on 2026-04-30 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(help_text='Nombre comercial del medicamento', max_length=100)),
                ('concentracion', models.CharField(help_text='Concentración del medicamento (ej. 500mg, 250mg)', max_length=100)),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'ordering': ['nombre_comercial'],
            },
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del solicitante', max_length=100)),
                ('documento', models.CharField(help_text='Número de documento del solicitante', max_length=50, unique=True)),
                ('telegram_id', models.CharField(blank=True, help_text='ID de Telegram del solicitante', max_length=50, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de contacto', max_length=15, null=True)),
                ('direccion_beneficiario', models.CharField(blank=True, help_text='Dirección del beneficiario', max_length=255, null=True)),
                ('edad', models.PositiveIntegerField(blank=True, help_text='Edad del solicitante', null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de registro')),
                ('verificado', models.BooleanField(default=False, help_text='Indica si el solicitante fue verificado mediante OCR de fórmula médica')),
            ],
            options={
                'verbose_name': 'Solicitante',
                'verbose_name_plural': 'Solicitantes',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitud_propia', models.BooleanField(default=True, help_text='Indica si la solicitud es propia del solicitante o de un tercero')),
                ('fecha', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la solicitud')),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', help_text='Prioridad de la solicitud', max_length=50)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('entregada', 'Entregada')], default='pendiente', help_text='Estado de la solicitud', max_length=50)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales', null=True)),
                ('solicitante', models.ForeignKey(help_text='Solicitante que realiza la solicitud', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='stock.solicitante')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_formula', models.FileField(help_text='Archivo de la fórmula solicitada', upload_to='formulas/')),
                ('texto_ocr', models.TextField(blank=True, help_text='Texto extraído del archivo (uso interno del administrador)', null=True)),
                ('solicitud', models.ForeignKey(help_text='Solicitud a la que pertenece la fórmula', on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to='stock.solicitud')),
            ],
            options={
                'verbose_name': 'Fórmula',
                'verbose_name_plural': 'Fórmulas',
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se realizó la entrega')),
                ('persona_que_entrega', models.CharField(blank=True, help_text='Nombre de la persona que entrega la solicitud', max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales sobre la entrega', null=True)),
                ('solicitud', models.OneToOneField(help_text='Solicitud a la que pertenece la entrega', on_delete=django.db.models.deletion.CASCADE, related_name='entrega', to='stock.solicitud')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
            },
        ),
        migrations.CreateModel(
            name='DetalleSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_entregada', models.PositiveIntegerField(blank=True, help_text='Cantidad de sobres entregados', null=True)),
                ('medicamento', models.ForeignKey(help_text='Medicamento solicitado', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='stock.medicamento')),
                ('solicitud', models.ForeignKey(help_text='Solicitud a la que pertenece el detalle', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='stock.solicitud')),
            ],
            options={
                'verbose_name': 'Detalle de Solicitud',
                'verbose_name_plural': 'Detalles de Solicitud',
            },
        ),
    ]
