# Generated by Django 5.2 on 2025-06-08 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_donante', models.CharField(choices=[('empresa', 'Empresa'), ('particular', 'Particular'), ('organizacion', 'Organización')], max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('canal_donacion', models.CharField(blank=True, help_text='Canal a través del cual se realizó la donación (ej. email, teléfono, etc.)', max_length=100, null=True)),
                ('verificado', models.BooleanField(default=False, help_text='Indica si el donante ha sido verificado por la organización')),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(help_text='Nombre comercial del medicamento', max_length=100)),
                ('presentacion', models.CharField(help_text='Presentación del medicamento (ej. tableta, jarabe, etc.)', max_length=100)),
                ('condiciones_almacenamiento', models.TextField(help_text='Condiciones de almacenamiento del medicamento (ej. temperatura, humedad, etc.)')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'ordering': ['nombre_comercial'],
            },
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del solicitante', max_length=100)),
                ('documento', models.CharField(help_text='Número de documento del solicitante (ej. DNI, pasaporte, etc.)', max_length=50)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de contacto del solicitante', max_length=15, null=True)),
                ('direccion_beneficiario', models.CharField(blank=True, help_text='Dirección del beneficiario de la solicitud (si es diferente al solicitante)', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_donacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se realizó la donación')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales sobre la donación', null=True)),
                ('donante', models.ForeignKey(help_text='Donante que realizó la donación', on_delete=django.db.models.deletion.CASCADE, related_name='donaciones', to='stock.donante')),
            ],
            options={
                'verbose_name': 'Donación',
                'verbose_name_plural': 'Donaciones',
                'ordering': ['-fecha_donacion'],
            },
        ),
        migrations.CreateModel(
            name='MedicamentoDonado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vencimiento', models.DateField(help_text='Fecha de vencimiento del medicamento')),
                ('lote', models.CharField(help_text='Número de lote del medicamento', max_length=50)),
                ('cantidad', models.PositiveIntegerField(default=0, help_text='Cantidad disponible del medicamento')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se ingresó el medicamento al sistema')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('entregado', 'Entregado'), ('vencido', 'Vencido')], default='disponible', help_text='Estado del medicamento (ej. disponible, reservado, entregado, vencido)', max_length=50)),
                ('donacion', models.ForeignKey(help_text='Donación a la que pertenece el medicamento', on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos_donados', to='stock.donacion')),
                ('medicamento', models.ForeignKey(help_text='Medicamento donado', on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos_donados', to='stock.medicamento')),
            ],
            options={
                'verbose_name': 'Medicamento Donado',
                'verbose_name_plural': 'Medicamentos Donados',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se realizó la solicitud')),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', help_text='Prioridad de la solicitud (ej. alta, media, baja)', max_length=50)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', help_text='Estado de la solicitud (ej. pendiente, aceptada, rechazada)', max_length=50)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales sobre la solicitud', null=True)),
                ('solicitante', models.ForeignKey(help_text='Solicitante que realiza la solicitud', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='stock.solicitante')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_formula', models.FileField(help_text='Archivo de la fórmula solicitada', upload_to='formulas/')),
                ('solicitud', models.ForeignKey(help_text='Solicitud a la que pertenece la fórmula', on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to='stock.solicitud')),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se realizó la entrega de la solicitud')),
                ('persona_que_entrega', models.CharField(blank=True, help_text='Nombre de la persona que entrega la solicitud', max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales sobre la entrega de la solicitud', null=True)),
                ('solicitud', models.OneToOneField(help_text='Solicitud a la que pertenece la entrega', on_delete=django.db.models.deletion.CASCADE, related_name='entrega', to='stock.solicitud')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.PositiveIntegerField(default=0, help_text='Cantidad solicitada del medicamento')),
                ('cantidad_entregada', models.PositiveIntegerField(default=0, help_text='Cantidad entregada del medicamento')),
                ('medicamento', models.ForeignKey(help_text='Medicamento solicitado', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='stock.medicamento')),
                ('solicitud', models.ForeignKey(help_text='Solicitud a la que pertenece el detalle', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='stock.solicitud')),
            ],
        ),
    ]
