# Generated by Django 5.2 on 2026-05-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitante',
            name='telegram_id',
            field=models.CharField(blank=True, help_text='ID de Telegram del solicitante', max_length=50, null=True),
        ),
    ]
