# Generated by Django 5.2 on 2025-07-03 03:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitante',
            name='edad',
            field=models.PositiveIntegerField(blank=True, help_text='Edad del solicitante (opcional)', null=True),
        ),
        migrations.AddField(
            model_name='solicitante',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Fecha y hora en que se registró el solicitante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='solicitud_propia',
            field=models.BooleanField(default=True, help_text='Indica si la solicitud es propia del solicitante o de un tercero'),
        ),
    ]
