# Generated by Django 5.2 on 2025-07-06 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_solicitante_edad_solicitante_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitante',
            name='telegram_id',
            field=models.CharField(blank=True, help_text='ID de Telegram del solicitante (opcional)', max_length=50, null=True),
        ),
    ]
