# Generated by Django 5.2 on 2026-06-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_solicitante_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='acta_generada',
            field=models.BooleanField(default=False, verbose_name='Acta generada'),
        ),
    ]
