# Generated by Django 5.2 on 2026-09-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_load_initial_medicamentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones adicionales. Este texto se incluye en el mensaje de Telegram que se envía al solicitante al notificar la aceptación o el rechazo de la solicitud, por lo que debe redactarse pensando en que el usuario lo leerá (ej. motivo del rechazo o indicaciones para la entrega).', null=True),
        ),
    ]
