# Generated by Django 5.2 on 2025-07-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_solicitante_telegram_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicamento',
            old_name='presentacion',
            new_name='forma_farmaceutica',
        ),
        migrations.AddField(
            model_name='medicamento',
            name='concentracion',
            field=models.CharField(default='', help_text='Concentración del medicamento (ej. 500mg, 250mg, etc.)', max_length=100),
            preserve_default=False,
        ),
    ]
