# Generated by Django 5.2 on 2026-06-16 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_entrega_acta_generada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='prioridad',
        ),
    ]
