# Generated by Django 5.2 on 2026-06-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_remove_solicitud_prioridad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitante',
            name='edad',
        ),
        migrations.AddField(
            model_name='detallesolicitud',
            name='tipo_presentacion',
            field=models.CharField(blank=True, choices=[('SP', 'Sobre (con pastillas)'), ('SO', 'Sobre (en polvo)'), ('FR', 'Frasco (Jarabe / Gotas)'), ('TU', 'Tubo (Crema)'), ('CJ', 'Caja completa'), ('PS', 'Pieza suelta'), ('SA', 'Sonda de alimentación')], help_text='Presentación del medicamento entregado', max_length=2, null=True),
        ),
    ]
