# Generated by Django 5.2 on 2025-08-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_rename_presentacion_medicamento_forma_farmaceutica_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='detallesolicitud',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_entregada__lte', models.F('cantidad_solicitada'))), name='cantidad_entregada_no_mayor_que_solicitada'),
        ),
    ]
