# Generated by Django 5.2 on 2025-09-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_detallesolicitud_cantidad_entregada_no_mayor_que_solicitada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='pendiente', help_text='Estado de la solicitud (ej. pendiente, aceptada, rechazada)', max_length=50),
        ),
    ]
