# Generated by Django 5.2 on 2026-06-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_remove_solicitante_edad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallesolicitud',
            name='tipo_presentacion',
            field=models.CharField(blank=True, choices=[('SP', 'Sobre (con Pastillas)'), ('SO', 'Sobre (en Polvo)'), ('FR', 'Frasco (Jarabe / Gotas)'), ('TU', 'Tubo (Crema)'), ('CJ', 'Caja Completa'), ('PS', 'Pieza Suelta'), ('SA', 'Sonda de Alimentación')], help_text='Presentación del medicamento entregado', max_length=2, null=True, verbose_name='TIPO DE PRESENTACIÓN'),
        ),
    ]
