# Generated by Django 5.2 on 2026-06-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_alter_detallesolicitud_tipo_presentacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='notificada_aceptacion',
            field=models.BooleanField(default=False, verbose_name='Notificación de aceptación de solicitud enviada'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='notificada_rechazo',
            field=models.BooleanField(default=False, verbose_name='Notificación de rechazo de solicitud enviada'),
        ),
    ]
