# Generated by Django 5.2 on 2026-02-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_alter_solicitud_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='texto_ocr',
            field=models.TextField(blank=True, help_text='Texto extraído por OCR del archivo (uso interno del administrador)', null=True),
        ),
        migrations.AddField(
            model_name='solicitante',
            name='verificado',
            field=models.BooleanField(default=False, help_text='Indica si el solicitante fue verificado mediante OCR de fórmula médica'),
        ),
    ]
