# Generated by Django 5.2 on 2026-05-05 17:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(help_text='Cantidad de sobres disponibles')),
                ('notas_adicionales', models.TextField(blank=True, help_text='Información adicional del anuncio, como fecha de vencimiento o tiempo vigente', null=True)),
                ('fecha_anuncio', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha en que se realiza el anuncio')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el anuncio sigue vigente')),
                ('medicamento', models.ForeignKey(help_text='Medicamento disponible para anunciar', on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to='stock.medicamento')),
            ],
            options={
                'verbose_name': 'Anuncio',
                'verbose_name_plural': 'Anuncios',
                'ordering': ['-fecha_anuncio'],
            },
        ),
    ]
