# Generated by Django 5.2 on 2026-06-16 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anuncio',
            options={'ordering': ['-fecha_anuncio'], 'verbose_name': 'Aviso', 'verbose_name_plural': 'Avisos'},
        ),
    ]
