# Generated by Django 5.2 on 2026-07-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='tipo_presentacion',
            field=models.CharField(blank=True, choices=[('SP', 'Sobre (con Pastillas)'), ('SO', 'Sobre (en Polvo)'), ('FR', 'Frasco (Jarabe / Gotas)'), ('TU', 'Tubo (Crema)'), ('CJ', 'Caja Completa'), ('PS', 'Pieza Suelta'), ('SA', 'Sonda de Alimentación')], help_text='Presentación del medicamento anunciado (sobre, frasco, caja, etc.)', max_length=2, null=True, verbose_name='Presentación'),
        ),
    ]
