# Generated by Django 5.2 on 2026-02-23 23:57

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticaDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('contenido_html', models.TextField()),
                ('fecha_vigencia', models.DateField()),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('es_activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-fecha_vigencia'],
            },
        ),
        migrations.CreateModel(
            name='AceptacionPolitica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat_id', models.CharField(max_length=50, unique=True)),
                ('fecha_consentimiento', models.DateField(default=datetime.date.today)),
                ('hora_consentimiento', models.TimeField(blank=True, null=True)),
                ('acepto', models.BooleanField(default=True)),
                ('fecha_hora_completa', models.DateTimeField(default=django.utils.timezone.now)),
                ('politica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='politicas.politicadatos')),
            ],
            options={
                'ordering': ['-fecha_hora_completa'],
            },
        ),
    ]
