# Generated by Django 5.2 on 2026-06-18 21:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticaDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('contenido_html', models.TextField()),
                ('fecha_vigencia', models.DateField()),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('es_activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Política de datos',
                'verbose_name_plural': 'Políticas de datos',
                'ordering': ['-fecha_vigencia'],
            },
        ),
    ]
