# Generated by Django 5.2

from django.db import migrations
import datetime

def seed_politica(apps, schema_editor):
    PoliticaDatos = apps.get_model('politicas', 'PoliticaDatos')
    
    contenido_html = """
<h2>1. Identificación del Responsable del Tratamiento</h2>
<p>El responsable del tratamiento de los datos personales es el <strong>Sistema de Donación de Medicamentos (SaludDonar Bot)</strong>, una plataforma comunitaria y solidaria dedicada a la distribución ética y segura de medicamentos donados.</p>
<p><strong>Correo electrónico de atención:</strong> protecciondatos@donacionmedicamentos.org</p>
<p><strong>Canal de contacto:</strong> Chatbot de Telegram (SaludDonar Bot)</p>

<h2>2. Datos Personales Recolectados</h2>
<p>Para la gestión de donaciones, recolectamos y procesamos los siguientes datos:</p>
<ul>
    <li><strong>Datos identificativos:</strong> Nombre completo, número y tipo de documento de identidad, edad, dirección física y número de teléfono.</li>
    <li><strong>Identificador de Telegram (Chat ID):</strong> Requerido para la interacción técnica con el chatbot.</li>
    <li><strong>Datos sensibles de salud:</strong> Imagen de la fórmula médica, texto extraído por OCR, medicamento solicitado y dosis, para validar que la entrega se realice bajo prescripción médica profesional.</li>
</ul>

<h2>3. Finalidad del Tratamiento de Datos</h2>
<p>Los datos recolectados se utilizan exclusivamente para:</p>
<ul>
    <li>Registrar y gestionar las solicitudes de donación de medicamentos.</li>
    <li>Verificar la autenticidad y vigencia de la fórmula médica adjunta.</li>
    <li>Priorizar las solicitudes según el stock de donaciones disponible y la urgencia médica.</li>
    <li>Coordinar la entrega física del beneficio al usuario o su acudiente.</li>
</ul>

<h2>4. Derechos de los Titulares</h2>
<p>De acuerdo con la legislación de protección de datos (Ley 1581 de 2012), usted tiene derecho a:</p>
<ul>
    <li>Conocer, actualizar y rectificar sus datos personales.</li>
    <li>Solicitar la supresión de sus datos o revocar la autorización cuando no exista un deber legal o contractual que lo impida.</li>
    <li>Acceder de forma gratuita a sus datos personales en nuestro sistema.</li>
</ul>

<h2>5. Procedimiento para Consultas y Reclamos</h2>
<p>Para ejercer sus derechos, puede enviar un correo a <strong>protecciondatos@donacionmedicamentos.org</strong> indicando su nombre completo, documento de identidad y el motivo de su solicitud. Su consulta o reclamo será atendido en los términos y plazos previstos por la ley colombiana.</p>

<h2>6. Seguridad y Conservación</h2>
<p>Los datos y fórmulas médicas se almacenan localmente de forma segura en nuestro servidor web y no se comparten con terceros. La validación de la información es realizada manualmente por el líder comunitario encargado del inventario. Los datos se conservarán hasta que el usuario solicite su eliminación o mientras sea necesario para la auditoría de las entregas físicas.</p>

<h2>7. Vigencia</h2>
<p>Esta política tiene vigencia a partir del 10 de junio de 2026.</p>
"""
    PoliticaDatos.objects.update_or_create(
        version="1.0",
        defaults={
            "titulo": "Política de Tratamiento de Datos Personales",
            "contenido_html": contenido_html.strip(),
            "fecha_vigencia": datetime.date(2026, 6, 10),
            "es_activa": True
        }
    )

def reverse_seed(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('politicas', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_politica, reverse_seed),
    ]
