# Generated by Django 5.2 on 2026-06-16 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('politicas', '0002_seed_politica_datos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='politicadatos',
            options={'ordering': ['-fecha_vigencia'], 'verbose_name': 'Política de datos', 'verbose_name_plural': 'Políticas de datos'},
        ),
        migrations.DeleteModel(
            name='AceptacionPolitica',
        ),
    ]
